using System.Text;
using System.Text.Json;
using RcNode;

namespace RcNode.Tests;

/// <summary>
/// Unit tests against the known vectors in conformance/vectors.json (generated by running
/// the reference PHP functions verbatim), plus a few checks of this port's own plumbing.
/// Usage: rc-node-tests [path/to/vectors.json]   (default: searched upwards from here)
/// </summary>
internal static class Tests
{
    private static int _pass, _fail;

    private static void Check(string group, string name, bool ok, string detail = "")
    {
        if (ok) { _pass++; return; }
        _fail++;
        Console.WriteLine("FAIL " + group + "/" + name + (detail != "" ? ": " + detail : ""));
    }

    private static string Show(string? s) => s == null ? "null" : JsonSerializer.Serialize(s);

    private static string? FindVectors(string[] args)
    {
        if (args.Length > 0) { return args[0]; }
        foreach (string start in new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory })
        {
            for (var d = new DirectoryInfo(start); d != null; d = d.Parent)
            {
                string p = Path.Combine(d.FullName, "conformance", "vectors.json");
                if (File.Exists(p)) { return p; }
            }
        }
        return null;
    }

    public static int Main(string[] args)
    {
        string? path = FindVectors(args);
        if (path == null) { Console.WriteLine("conformance/vectors.json not found - pass its path as the first argument."); return 2; }
        using var doc = JsonDocument.Parse(File.ReadAllBytes(path));
        var v = doc.RootElement;

        Signatures(v);
        Clean(v);
        Numbers(v);
        StreamCut(v);
        Sse(v);
        Embeddings(v);
        Images(v);
        Constants(v);
        Plumbing();

        Console.WriteLine((_fail == 0 ? "OK" : "FAILED") + ": " + _pass + " passed, " + _fail + " failed (" + path + ")");
        return _fail == 0 ? 0 : 1;
    }

    private static void Signatures(JsonElement v)
    {
        foreach (var t in v.GetProperty("signature").EnumerateArray())
        {
            string name = t.GetProperty("name").GetString()!;
            string secret = t.GetProperty("secret").GetString()!;
            string ts = t.GetProperty("ts").GetString()!;
            string method = t.GetProperty("method").GetString()!;
            string p = t.GetProperty("path").GetString()!;
            string q = t.GetProperty("query").GetString()!;
            byte[] body = Encoding.UTF8.GetBytes(t.GetProperty("body").GetString()!);
            string expected = t.GetProperty("expected_hex").GetString()!;
            string got = Signature.Sign(secret, ts, method, p, q, body);
            Check("signature", name, got == expected, "got " + got + ", expected " + expected);

            // The URI the node sends must carry exactly the signed path and query.
            var uri = new Uri("https://reactive.example" + p + "?" + q);
            Check("signature", name + "/uri_roundtrip", uri.AbsolutePath == p && uri.Query == "?" + q,
                  "path " + uri.AbsolutePath + ", query " + uri.Query);
            string sts = t.GetProperty("string_to_sign").GetString()!;
            Check("signature", name + "/string_to_sign",
                  sts == "RC-KI-v2\n" + ts + "\n" + method + "\n" + p + "\n" + q + "\n" + t.GetProperty("body").GetString());
        }
        string nonce = Signature.Nonce();
        Check("signature", "nonce_16_hex", nonce.Length == 16 && nonce.All(ch => ch is >= '0' and <= '9' or >= 'a' and <= 'f'), nonce);
    }

    private static void Clean(JsonElement v)
    {
        foreach (var t in v.GetProperty("clean").EnumerateArray())
        {
            string name = t.GetProperty("name").GetString()!;
            string expected = t.GetProperty("expected").GetString()!;
            string got = TextRules.Clean(t.GetProperty("input").GetString()!);
            Check("clean", name, got == expected, "got " + Show(got) + ", expected " + Show(expected));
        }
    }

    private static void Numbers(JsonElement v)
    {
        foreach (var t in v.GetProperty("numbers").EnumerateArray())
        {
            string name = t.GetProperty("name").GetString()!;
            var e = t.GetProperty("expected");
            string? expected = e.ValueKind == JsonValueKind.Null ? null : e.ToString();
            string? got = TextRules.NumberCheck(t.GetProperty("text").GetString()!, t.GetProperty("facts").GetString()!);
            Check("numbers", name, got == expected, "got " + Show(got) + ", expected " + Show(expected));
        }
    }

    private static void StreamCut(JsonElement v)
    {
        foreach (var t in v.GetProperty("stream_cut").EnumerateArray())
        {
            string name = t.GetProperty("name").GetString()!;
            string expected = t.GetProperty("expected").GetString()!;
            string got = TextRules.StreamCut(t.GetProperty("input").GetString()!);
            Check("stream_cut", name, got == expected, "got " + Show(got) + ", expected " + Show(expected));
        }
    }

    private static void Sse(JsonElement v)
    {
        foreach (var t in v.GetProperty("sse").EnumerateArray())
        {
            string name = t.GetProperty("name").GetString()!;
            var s = new StreamState();
            foreach (var chunk in t.GetProperty("chunks_b64").EnumerateArray())
            {
                s.Feed(Convert.FromBase64String(chunk.GetString()!));
            }
            s.Finish();
            var ex = t.GetProperty("expected");
            Check("sse", name + "/text", s.Text == ex.GetProperty("text").GetString(), "got " + Show(s.Text));
            Check("sse", name + "/sse", s.Sse == ex.GetProperty("sse").GetBoolean());
            Check("sse", name + "/has_content", s.Content == ex.GetProperty("has_content").GetBoolean());
            Check("sse", name + "/ended", s.End == ex.GetProperty("ended").GetBoolean());
            Check("sse", name + "/error", s.Error == ex.GetProperty("error").GetString(), "got " + Show(s.Error));

            var er = t.GetProperty("expected_result");
            var textEl = er.GetProperty("text");
            string? expText = textEl.ValueKind == JsonValueKind.Null ? null : textEl.GetString();
            string expErr = er.GetProperty("fehler").GetString()!;
            var m = Answers.ReadModel(new HttpResult { Code = 200 }, 0, s);
            Check("sse", name + "/result", m.Text == expText && m.Error == expErr,
                  "got " + Show(m.Text) + " / " + Show(m.Error) + ", expected " + Show(expText) + " / " + Show(expErr));
        }
    }

    private static void Embeddings(JsonElement v)
    {
        foreach (var t in v.GetProperty("embed_result").EnumerateArray())
        {
            string name = t.GetProperty("name").GetString()!;
            var r = new HttpResult
            {
                Code = t.GetProperty("http_status").GetInt32(),
                Body = Encoding.UTF8.GetBytes(t.GetProperty("body").GetString()!),
                Error = t.GetProperty("transport_error").GetString()!,
            };
            var er = t.GetProperty("expected_result");
            string? expected = er.ValueKind == JsonValueKind.Null ? null : er.GetString();
            string expErr = t.GetProperty("expected_error").GetString()!;
            var (payload, error, _) = Answers.ReadEmbedding(r, t.GetProperty("text_count").GetInt32(), t.GetProperty("embed_model").GetString()!);
            Check("embed_result", name, payload == expected && error == expErr,
                  "got " + Show(payload) + " / " + Show(error) + ", expected " + Show(expected) + " / " + Show(expErr));
        }
    }

    private static void Images(JsonElement v)
    {
        foreach (var t in v.GetProperty("images").EnumerateArray())
        {
            string name = t.GetProperty("name").GetString()!;
            JsonElement? input = t.TryGetProperty("input", out var inp) && inp.ValueKind != JsonValueKind.Null ? inp : null;
            var got = TextRules.ImagesFromJob(input, t.GetProperty("images").GetBoolean(), t.GetProperty("images_max").GetInt32());
            var expected = t.GetProperty("expected").EnumerateArray().Select(x => x.GetString()!).ToList();
            Check("images", name, got.SequenceEqual(expected), "got " + got.Count + " image(s), expected " + expected.Count);
        }
    }

    private static void Constants(JsonElement v)
    {
        Check("constants", "retry_suffix", Worker.RetrySuffix == v.GetProperty("retry_suffix").GetString());
        var c = v.GetProperty("constants");
        Check("constants", "probe_system", c.GetProperty("probe_system").GetString() == "Antworte mit genau einem Wort.");
        Check("constants", "probe_prompt", c.GetProperty("probe_prompt").GetString() == "Sag: Bereit");
    }

    /// <summary>This port's own plumbing: json_encode compatibility and the model request body.</summary>
    private static void Plumbing()
    {
        string sample = "a/b \"q\" \\ \n\t" + (char)0x01 + " " + (char)0xFC + " " + (char)0x2028 + " " + char.ConvertFromUtf32(0x1F600);
        Check("json", "unescaped_unicode",
              Php.Encode(sample, unescapedUnicode: true) == "\"a\\/b \\\"q\\\" \\\\ \\n\\t\\u0001 " + (char)0xFC + " \\u2028 " + char.ConvertFromUtf32(0x1F600) + "\"",
              Php.Encode(sample, unescapedUnicode: true));
        Check("json", "escaped_unicode",
              Php.Encode(sample, unescapedUnicode: false, unescapedSlashes: true) == "\"a/b \\\"q\\\" \\\\ \\n\\t\\u0001 \\u00fc \\u2028 \\ud83d\\ude00\"",
              Php.Encode(sample, unescapedUnicode: false, unescapedSlashes: true));
        Check("json", "floats", Php.FormatDouble(0.2) == "0.2" && Php.FormatDouble(1) == "1.0" && Php.FormatDouble(0) == "0.0"
                                && Php.FormatDouble(1e25) == "1.0e+25" && Php.FormatDouble(1e-5) == "1.0e-5");

        var cfg = Config.FromJson(JsonDocument.Parse(
            "{\"base_url\":\"https://x.example\",\"node_id\":\"kn-1\",\"secret\":\"s\",\"model\":\"m\",\"model_endpoint\":\"http://127.0.0.1:1/v1/\",\"temperature\":1}").RootElement);
        var net = new Net(cfg);
        string body = Encoding.UTF8.GetString(net.ModelBody("S", "P" + (char)0xE4, 0, Array.Empty<string>(), false));
        Check("model_body", "text", body == "{\"model\":\"m\",\"stream\":false,\"temperature\":1.0,\"max_tokens\":300,\"messages\":[{\"role\":\"system\",\"content\":\"S\"},{\"role\":\"user\",\"content\":\"P" + (char)0xE4 + "\"}]}", body);
        body = Encoding.UTF8.GetString(net.ModelBody("S", "P", 50, new[] { "data:image/png;base64,AA==" }, true));
        Check("model_body", "image", body == "{\"model\":\"m\",\"stream\":true,\"temperature\":1.0,\"max_tokens\":50,\"messages\":[{\"role\":\"system\",\"content\":\"S\"},{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\"P\"},{\"type\":\"image_url\",\"image_url\":{\"url\":\"data:image\\/png;base64,AA==\"}}]}]}", body);
        Check("config", "model_url", cfg.ModelUrl == "http://127.0.0.1:1/v1/chat/completions" && cfg.ModelsUrl == "http://127.0.0.1:1/v1/models", cfg.ModelUrl);

        var aliases = Config.FromJson(JsonDocument.Parse(
            "{\"base_url\":\"https://x.example\",\"node_id\":\"kn-1\",\"secret\":\"s\",\"model\":\"m\",\"chat_url\":\"https://az.example/c\",\"kinds\":[\"chat\",\"translation\",\"summary\"],\"capabilities\":[\"chat\",\"embedding\"]}").RootElement);
        Check("config", "kind_aliases", string.Join(",", aliases.Kinds) == "chat,uebersetzung,zusammenfassung"
                                        && string.Join(",", aliases.EffectiveCapabilities) == "chat,einbettung");
        bool threw = false;
        try { Config.FromJson(JsonDocument.Parse("{\"base_url\":\"https://x\",\"node_id\":\"n-1\",\"secret\":\"s\",\"model\":\"m\",\"model_endpoint\":\"http://a/v1\"}").RootElement); }
        catch (ConfigException) { threw = true; }
        Check("config", "node_id_prefix", threw);
        var r = ResolveEntry.Parse("reactive.chat:443:127.0.0.1");
        Check("config", "resolve", r.Matches("REACTIVE.chat", 443) && !r.Matches("reactive.chat", 80) && r.Addresses[0].ToString() == "127.0.0.1");

        Check("text", "no_answer", TextRules.ContainsNoAnswer("x keine_antwort y") && !TextRules.ContainsNoAnswer("KEINE ANTWORT"));
        Check("text", "substr_code_points", TextRules.Substr("a" + char.ConvertFromUtf32(0x1F600) + "b", 2) == "a" + char.ConvertFromUtf32(0x1F600));
    }
}
