'use strict';
/**
 * Known vectors from conformance/vectors.json (generated by running the
 * reference PHP functions): signature, clean-up, number check, stream cut,
 * SSE parsing, embedding result, image filter.
 *
 *   node --test test/        (from node/)
 * RC_NODE_VECTORS=path overrides the location of vectors.json.
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const logic = require('../lib/logic');

const file = process.env.RC_NODE_VECTORS || path.join(__dirname, '..', '..', 'conformance', 'vectors.json');
const V = JSON.parse(fs.readFileSync(file, 'utf8'));

test('retry suffix is the reference text', () => {
  assert.equal(logic.RETRY_SUFFIX, V.retry_suffix);
});

test('signature', async (t) => {
  for (const c of V.signature) {
    await t.test(c.name, () => {
      assert.equal(logic.stringToSign(c.ts, c.method, c.path, c.query, c.body), c.string_to_sign);
      assert.equal(logic.sign(c.secret, c.ts, c.method, c.path, c.query, c.body), c.expected_hex);
    });
  }
});

test('clean-up (saeubern)', async (t) => {
  for (const c of V.clean) {
    await t.test(c.name, () => assert.equal(logic.clean(c.input), c.expected));
  }
});

test('number check (zahlenPruefen)', async (t) => {
  for (const c of V.numbers) {
    await t.test(c.name, () => assert.equal(logic.checkNumbers(c.text, c.facts), c.expected));
  }
});

test('stream cut (stromSchnitt)', async (t) => {
  for (const c of V.stream_cut) {
    await t.test(c.name, () => assert.equal(logic.streamCut(c.input), c.expected));
  }
});

test('SSE parsing', async (t) => {
  for (const c of V.sse) {
    await t.test(c.name, () => {
      const s = new logic.StreamState();
      for (const b of c.chunks_b64) s.feed(Buffer.from(b, 'base64'));
      s.finish();
      assert.deepEqual({ text: s.text, sse: s.sse, has_content: s.hasContent, ended: s.ended, error: s.error },
        c.expected);
      const m = logic.readModel(200, s.raw, '', 0, s);
      assert.deepEqual({ text: m.text, fehler: m.fehler }, c.expected_result);
    });
  }
});

test('embedding result (einbettenLesen)', async (t) => {
  for (const c of V.embed_result) {
    await t.test(c.name, () => {
      const [r, f] = logic.readEmbedding(c.http_status, c.body, c.transport_error, c.text_count, c.embed_model);
      assert.equal(r, c.expected_result);
      assert.equal(f, c.expected_error);
    });
  }
});

test('image filter (bilderAusAuftrag)', async (t) => {
  for (const c of V.images) {
    await t.test(c.name, () => {
      assert.deepEqual(logic.imagesFromJob(c.input, c.images, c.images_max), c.expected);
    });
  }
});
