# frozen_string_literal: true

# Known vectors from ../conformance/vectors.json (generated by running the
# reference PHP functions). Run: ruby test/run.rb   (or: rake test)
require 'minitest/autorun'
require 'json'
require_relative '../lib/rc_node'

VECTORS_PATH = ENV.fetch('RC_NODE_VECTORS', File.expand_path('../../conformance/vectors.json', __dir__))
VECTORS = JSON.parse(File.read(VECTORS_PATH, encoding: 'UTF-8'))

class TestVectors < Minitest::Test
  def self.each_case(section, prefix = section, &block)
    VECTORS.fetch(section).each_with_index do |c, i|
      define_method("test_#{prefix}_#{i}_#{c['name'].gsub(/\W/, '_')}") { block.call(self, c) }
    end
  end

  def test_retry_suffix
    assert_equal VECTORS['retry_suffix'], RcNode::Node::RETRY_SUFFIX
  end

  def test_probe_constants
    k = VECTORS['constants']
    assert_equal k['probe_system'], RcNode::Node::PROBE_SYSTEM
    assert_equal k['probe_prompt'], RcNode::Node::PROBE_PROMPT
    assert_equal k['heartbeat_s'], RcNode::Node::HEARTBEAT_S
    assert_equal k['teil_max_entries'], RcNode::Node::TEIL_MAX_ENTRIES
    assert_equal k['teil_max_bytes'], RcNode::Node::TEIL_MAX_BYTES
    assert_equal k['image_max_bytes'], RcNode::Text::IMAGE_MAX_BYTES
    assert_equal k['signature_prefix'], RcNode::Wire::SIGNATURE_PREFIX
  end

  each_case('signature') do |t, c|
    t.assert_equal c['expected_hex'],
                   RcNode::Wire.sign(c['secret'], c['ts'], c['method'], c['path'], c['query'], c['body'])
  end

  # The POST bodies in the signature vectors were written by PHP's
  # json_encode(): re-encoding them must give the same bytes.
  each_case('signature', 'json_body') do |t, c|
    next if c['body'].empty?

    t.assert_equal c['body'], RcNode::Php.json_encode(JSON.parse(c['body']))
  end

  each_case('clean') do |t, c|
    t.assert_equal c['expected'], RcNode::Text.clean(c['input'])
  end

  each_case('numbers') do |t, c|
    got = RcNode::Text.check_numbers(c['text'], c['facts'])
    c['expected'].nil? ? t.assert_nil(got) : t.assert_equal(c['expected'], got)
  end

  each_case('stream_cut') do |t, c|
    t.assert_equal c['expected'], RcNode::Text.stream_cut(c['input'])
  end

  each_case('sse') do |t, c|
    s = RcNode::StreamState.new
    c['chunks_b64'].each { |b| s.feed(b.unpack1('m')) }
    s.finish
    got = { 'text' => s.text, 'sse' => s.sse?, 'has_content' => s.has_content?,
            'ended' => s.ended?, 'error' => s.error }
    t.assert_equal c['expected'], got
    m = RcNode::Model.read(200, s.raw, '', 0, s)
    t.assert_equal c['expected_result'], { 'text' => m.text, 'fehler' => m.error }
  end

  each_case('embed_result') do |t, c|
    result, error = RcNode::Model.embed_result(c['http_status'], c['body'], c['transport_error'],
                                               c['text_count'], c['embed_model'])
    c['expected_result'].nil? ? t.assert_nil(result) : t.assert_equal(c['expected_result'], result)
    t.assert_equal c['expected_error'], error
  end

  each_case('images') do |t, c|
    t.assert_equal c['expected'], RcNode::Text.images_from_job(c['input'], c['images'], c['images_max'])
  end
end
