package main

// Unit tests against the shared known-answer vectors in
// ../conformance/vectors.json (generated by running the PHP reference).
// Set RC_VECTORS=/path/to/vectors.json to use another copy.

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

type vectors struct {
	RetrySuffix string `json:"retry_suffix"`
	Signature   []struct {
		Name, Secret, TS, Method, Path, Query, Body string
		StringToSign                                string `json:"string_to_sign"`
		ExpectedHex                                 string `json:"expected_hex"`
	}
	Clean []struct {
		Name, Input, Expected string
	}
	Numbers []struct {
		Name, Text, Facts string
		Expected          *string
	}
	StreamCut []struct {
		Name, Input, Expected string
	} `json:"stream_cut"`
	SSE []struct {
		Name     string
		Chunks   []string `json:"chunks_b64"`
		Expected struct {
			Text       string
			SSE        bool
			HasContent bool `json:"has_content"`
			Ended      bool
			Error      string
		}
		ExpectedResult struct {
			Text   *string
			Fehler string
		} `json:"expected_result"`
	}
	EmbedResult []struct {
		Name           string
		HTTPStatus     int     `json:"http_status"`
		Body           string  `json:"body"`
		TransportError string  `json:"transport_error"`
		TextCount      int     `json:"text_count"`
		EmbedModel     string  `json:"embed_model"`
		ExpectedResult *string `json:"expected_result"`
		ExpectedError  string  `json:"expected_error"`
	} `json:"embed_result"`
	Images []struct {
		Name      string
		Images    bool
		ImagesMax json.RawMessage `json:"images_max"`
		Input     json.RawMessage
		Expected  []string
	}
}

func loadVectors(t *testing.T) *vectors {
	t.Helper()
	p := os.Getenv("RC_VECTORS")
	if p == "" {
		p = "../conformance/vectors.json"
	}
	data, err := os.ReadFile(p)
	if err != nil {
		t.Skipf("no vectors (%v)", err)
	}
	var v vectors
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("vectors.json: %v", err)
	}
	// A section that decodes empty would make its test pass without testing.
	for name, n := range map[string]int{"signature": len(v.Signature), "clean": len(v.Clean),
		"numbers": len(v.Numbers), "stream_cut": len(v.StreamCut), "sse": len(v.SSE),
		"embed_result": len(v.EmbedResult), "images": len(v.Images)} {
		if n == 0 {
			t.Fatalf("vectors.json: section %s is empty or did not decode", name)
		}
	}
	return &v
}

func TestRetrySuffix(t *testing.T) {
	v := loadVectors(t)
	if v.RetrySuffix != retrySuffix {
		t.Errorf("retry suffix differs:\n got %q\nwant %q", retrySuffix, v.RetrySuffix)
	}
}

func TestSignatureVectors(t *testing.T) {
	v := loadVectors(t)
	if len(v.Signature) == 0 {
		t.Fatal("no signature vectors")
	}
	for _, c := range v.Signature {
		if got := sign(c.Secret, c.TS, c.Method, c.Path, c.Query, c.Body); got != c.ExpectedHex {
			t.Errorf("%s: got %s want %s", c.Name, got, c.ExpectedHex)
		}
	}
}

func TestCleanVectors(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.Clean {
		if got := cleanAnswer(c.Input); got != c.Expected {
			t.Errorf("%s: got %q want %q", c.Name, got, c.Expected)
		}
	}
}

func TestNumberVectors(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.Numbers {
		bad, has := checkNumbers(c.Text, c.Facts)
		switch {
		case c.Expected == nil && has:
			t.Errorf("%s: got %q want null", c.Name, bad)
		case c.Expected != nil && (!has || bad != *c.Expected):
			t.Errorf("%s: got %q (%v) want %q", c.Name, bad, has, *c.Expected)
		}
	}
}

func TestStreamCutVectors(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.StreamCut {
		if got := streamCut(c.Input); got != c.Expected {
			t.Errorf("%s: got %q want %q", c.Name, got, c.Expected)
		}
	}
}

func TestSSEVectors(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.SSE {
		s := &streamState{}
		for _, b := range c.Chunks {
			d, err := base64.StdEncoding.DecodeString(b)
			if err != nil {
				t.Fatalf("%s: %v", c.Name, err)
			}
			s.feed(d)
		}
		s.finish()
		e := c.Expected
		if string(s.text) != e.Text || s.sse != e.SSE || s.content != e.HasContent || s.done != e.Ended || s.errMsg != e.Error {
			t.Errorf("%s: got text=%q sse=%v content=%v ended=%v err=%q, want %+v",
				c.Name, s.text, s.sse, s.content, s.done, s.errMsg, e)
		}
		m := readModel(200, s.raw, "", 0, s)
		r := c.ExpectedResult
		if r.Text == nil {
			if m.ok || m.fail.wire != r.Fehler {
				t.Errorf("%s/result: got ok=%v text=%q fehler=%q, want fehler %q", c.Name, m.ok, m.text, m.fail.wire, r.Fehler)
			}
		} else if !m.ok || m.text != *r.Text || r.Fehler != "" {
			t.Errorf("%s/result: got ok=%v text=%q fehler=%q, want text %q", c.Name, m.ok, m.text, m.fail.wire, *r.Text)
		}
	}
}

func TestEmbedVectors(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.EmbedResult {
		got, ok, why := readEmbedding(c.HTTPStatus, []byte(c.Body), c.TransportError, c.TextCount, c.EmbedModel)
		if c.ExpectedResult != nil {
			if !ok || got != *c.ExpectedResult {
				t.Errorf("%s: got %q (%q) want %q", c.Name, got, why.wire, *c.ExpectedResult)
			}
		} else if ok || why.wire != c.ExpectedError {
			t.Errorf("%s: got ok=%v %q, want error %q", c.Name, ok, why.wire, c.ExpectedError)
		}
	}
}

func TestImageVectors(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.Images {
		in, ok := decodeJSON(c.Input)
		if !ok {
			t.Fatalf("%s: input does not decode", c.Name)
		}
		maxV, _ := decodeJSON(c.ImagesMax)
		got := imagesFromJob(in, c.Images, toInt(maxV))
		if len(got) == 0 && len(c.Expected) == 0 {
			continue
		}
		if !reflect.DeepEqual(got, c.Expected) {
			t.Errorf("%s: got %d images %.60q, want %d %.60q", c.Name, len(got), got, len(c.Expected), c.Expected)
		}
	}
}
